param(
    $resourcePackagesDirectory
)

$bootstrapVersions = @("Bootstrap5", "Bootstrap4")
$bootstrapDictionaries = @()
$newTemplatesDirectory = "$PSScriptRoot\..\content\ResourcePackages"

foreach($bv in $bootstrapVersions)
{
    $dictionary = Get-Content "$PSScriptRoot\$($bv).json" | ConvertFrom-Json
    $bootstrapDictionaries += $dictionary
}

function GetFileSHA256HashUTF8($filePath)
{
    $content = Get-Content -Path $filePath -Encoding UTF8
    if($content -imatch "generated by Sitefinity CLI")
    {
        $content = $content | Select-Object -Skip 5 # Removes the Sitefinity CLI generated comment lines
    }

    $bytes = [System.Text.Encoding]::UTF8.GetBytes($content)
    $stream = [System.IO.MemoryStream]::new($bytes)
    $hash = (Get-FileHash -InputStream $stream -Algorithm SHA256).Hash
    return $hash
}

function UpdateDefaultTemplateFile($templatesDictionary, $fileKey, $hash, $fileInfo, $templatesDictionaryName)
{
    try 
    {
        if($templatesDictionary."$fileKey" -and $templatesDictionary."$fileKey".Contains($hash))
        {
            $newTemplateFile = "$($newTemplatesDirectory)\$($templatesDictionaryName)\$($fileKey)"
            $destinationFile = $fileInfo.FullName
            $destinationDirectory = $fileInfo.Directory.FullName

            if((GetFileSHA256HashUTF8 -filePath $newTemplateFile) -ne (GetFileSHA256HashUTF8 -filePath $destinationFile))
            {
                Write-Host "Update $destinationFile with $newTemplateFile..."
                Copy-Item -Path $newTemplateFile -Destination $destinationFile -Force
            }

            if($fileKey.Contains("MVC\Views"))
            {
                $viewDirectory = Split-Path $fileKey
                $viewNewDirectory = "$($newTemplatesDirectory)\$($templatesDictionaryName)\$($viewDirectory)"
                if(Test-Path $viewNewDirectory)
                {
                    Get-ChildItem $viewNewDirectory | %{
                        if(!(Test-Path "$($destinationDirectory)\$($_.Name)"))
                        {
                            # Copy missing widget templates
                            Copy-Item $_.FullName -Destination $destinationDirectory -Force
                        }
                    }
                }
            }

            return $true
        }
    
        
    }
    catch 
    {
        Write-Host "FAILED to update '$($fileInfo.FullName)' template file!"
        Write-Warning $_.Exception.Message
    }

    return $false
}

Get-ChildItem $resourcePackagesDirectory -Directory -Exclude $bootstrapVersions | %{
    $customTemplatesDirectory = $_.FullName
    $packageVersionFile = "$($_.FullName)\package.json"
    if(Test-Path $packageVersionFile)
    {
        $packageVersionJson = Get-Content $packageVersionFile | ConvertFrom-Json
        if($packageVersionJson.name -eq "bootstrap-5-package")
        {
            $bootstrapVersion = "Bootstrap5"
            $currentBootstrapDictionary = $bootstrapDictionaries[0]
        }
        elseif($packageVersionJson.name -eq "bootstrap-4-package")
        {
            $bootstrapVersion = "Bootstrap4"         
            $currentBootstrapDictionary = $bootstrapDictionaries[1]   
        }
    }
    else
    {
        $bootstrapVersion = $null
        $currentBootstrapDictionary = $null
    }

    Get-ChildItem $_ -Recurse -File | %{
        $file = $_.FullName.Replace($customTemplatesDirectory, "").TrimStart("\")
        #$hash = (Get-FileHash -Path $_.FullName -Algorithm SHA256).Hash
        $hash = GetFileSHA256HashUTF8 -filePath $_.FullName

        if($bootstrapVersion -eq $null)
        {
            $index = 0
            foreach($bootstrapDictionary in $bootstrapDictionaries)
            {
                $updateResult = UpdateDefaultTemplateFile -templatesDictionary $bootstrapDictionary `
                                                          -fileKey $file `
                                                          -hash $hash `
                                                          -fileInfo $_ `
                                                          -templatesDictionaryName $bootstrapVersions[$index]
                if ($updateResult) 
                {
                    break;
                }

                $index++
            }
        }
        else
        {            
            $updateResult = UpdateDefaultTemplateFile -templatesDictionary $currentBootstrapDictionary `
                                                      -fileKey $file `
                                                      -hash $hash `
                                                      -fileInfo $_ `
                                                      -templatesDictionaryName $bootstrapVersion      
        }
    }
}
# SIG # Begin signature block
# MIIvyQYJKoZIhvcNAQcCoIIvujCCL7YCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCD10yynXnG1NSdd
# COKv7plwrGvnvLGVF/uAc2ioNCqnnKCCFA0wggVyMIIDWqADAgECAhB2U/6sdUZI
# k/Xl10pIOk74MA0GCSqGSIb3DQEBDAUAMFMxCzAJBgNVBAYTAkJFMRkwFwYDVQQK
# ExBHbG9iYWxTaWduIG52LXNhMSkwJwYDVQQDEyBHbG9iYWxTaWduIENvZGUgU2ln
# bmluZyBSb290IFI0NTAeFw0yMDAzMTgwMDAwMDBaFw00NTAzMTgwMDAwMDBaMFMx
# CzAJBgNVBAYTAkJFMRkwFwYDVQQKExBHbG9iYWxTaWduIG52LXNhMSkwJwYDVQQD
# EyBHbG9iYWxTaWduIENvZGUgU2lnbmluZyBSb290IFI0NTCCAiIwDQYJKoZIhvcN
# AQEBBQADggIPADCCAgoCggIBALYtxTDdeuirkD0DcrA6S5kWYbLl/6VnHTcc5X7s
# k4OqhPWjQ5uYRYq4Y1ddmwCIBCXp+GiSS4LYS8lKA/Oof2qPimEnvaFE0P31PyLC
# o0+RjbMFsiiCkV37WYgFC5cGwpj4LKczJO5QOkHM8KCwex1N0qhYOJbp3/kbkbuL
# ECzSx0Mdogl0oYCve+YzCgxZa4689Ktal3t/rlX7hPCA/oRM1+K6vcR1oW+9YRB0
# RLKYB+J0q/9o3GwmPukf5eAEh60w0wyNA3xVuBZwXCR4ICXrZ2eIq7pONJhrcBHe
# OMrUvqHAnOHfHgIB2DvhZ0OEts/8dLcvhKO/ugk3PWdssUVcGWGrQYP1rB3rdw1G
# R3POv72Vle2dK4gQ/vpY6KdX4bPPqFrpByWbEsSegHI9k9yMlN87ROYmgPzSwwPw
# jAzSRdYu54+YnuYE7kJuZ35CFnFi5wT5YMZkobacgSFOK8ZtaJSGxpl0c2cxepHy
# 1Ix5bnymu35Gb03FhRIrz5oiRAiohTfOB2FXBhcSJMDEMXOhmDVXR34QOkXZLaRR
# kJipoAc3xGUaqhxrFnf3p5fsPxkwmW8x++pAsufSxPrJ0PBQdnRZ+o1tFzK++Ol+
# A/Tnh3Wa1EqRLIUDEwIrQoDyiWo2z8hMoM6e+MuNrRan097VmxinxpI68YJj8S4O
# JGTfAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwIBhjAPBgNVHRMBAf8EBTADAQH/MB0G
# A1UdDgQWBBQfAL9GgAr8eDm3pbRD2VZQu86WOzANBgkqhkiG9w0BAQwFAAOCAgEA
# Xiu6dJc0RF92SChAhJPuAW7pobPWgCXme+S8CZE9D/x2rdfUMCC7j2DQkdYc8pzv
# eBorlDICwSSWUlIC0PPR/PKbOW6Z4R+OQ0F9mh5byV2ahPwm5ofzdHImraQb2T07
# alKgPAkeLx57szO0Rcf3rLGvk2Ctdq64shV464Nq6//bRqsk5e4C+pAfWcAvXda3
# XaRcELdyU/hBTsz6eBolSsr+hWJDYcO0N6qB0vTWOg+9jVl+MEfeK2vnIVAzX9Rn
# m9S4Z588J5kD/4VDjnMSyiDN6GHVsWbcF9Y5bQ/bzyM3oYKJThxrP9agzaoHnT5C
# JqrXDO76R78aUn7RdYHTyYpiF21PiKAhoCY+r23ZYjAf6Zgorm6N1Y5McmaTgI0q
# 41XHYGeQQlZcIlEPs9xOOe5N3dkdeBBUO27Ql28DtR6yI3PGErKaZND8lYUkqP/f
# obDckUCu3wkzq7ndkrfxzJF0O2nrZ5cbkL/nx6BvcbtXv7ePWu16QGoWzYCELS/h
# AtQklEOzFfwMKxv9cW/8y7x1Fzpeg9LJsy8b1ZyNf1T+fn7kVqOHp53hWVKUQY9t
# W76GlZr/GnbdQNJRSnC0HzNjI3c/7CceWeQIh+00gkoPP/6gHcH1Z3NFhnj0qinp
# J4fGGdvGExTDOUmHTaCX4GUT9Z13Vunas1jHOvLAzYIwggboMIIE0KADAgECAhB3
# vQ4Ft1kLth1HYVMeP3XtMA0GCSqGSIb3DQEBCwUAMFMxCzAJBgNVBAYTAkJFMRkw
# FwYDVQQKExBHbG9iYWxTaWduIG52LXNhMSkwJwYDVQQDEyBHbG9iYWxTaWduIENv
# ZGUgU2lnbmluZyBSb290IFI0NTAeFw0yMDA3MjgwMDAwMDBaFw0zMDA3MjgwMDAw
# MDBaMFwxCzAJBgNVBAYTAkJFMRkwFwYDVQQKExBHbG9iYWxTaWduIG52LXNhMTIw
# MAYDVQQDEylHbG9iYWxTaWduIEdDQyBSNDUgRVYgQ29kZVNpZ25pbmcgQ0EgMjAy
# MDCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAMsg75ceuQEyQ6BbqYoj
# /SBerjgSi8os1P9B2BpV1BlTt/2jF+d6OVzA984Ro/ml7QH6tbqT76+T3PjisxlM
# g7BKRFAEeIQQaqTWlpCOgfh8qy+1o1cz0lh7lA5tD6WRJiqzg09ysYp7ZJLQ8LRV
# X5YLEeWatSyyEc8lG31RK5gfSaNf+BOeNbgDAtqkEy+FSu/EL3AOwdTMMxLsvUCV
# 0xHK5s2zBZzIU+tS13hMUQGSgt4T8weOdLqEgJ/SpBUO6K/r94n233Hw0b6nskEz
# IHXMsdXtHQcZxOsmd/KrbReTSam35sOQnMa47MzJe5pexcUkk2NvfhCLYc+YVaMk
# oog28vmfvpMusgafJsAMAVYS4bKKnw4e3JiLLs/a4ok0ph8moKiueG3soYgVPMLq
# 7rfYrWGlr3A2onmO3A1zwPHkLKuU7FgGOTZI1jta6CLOdA6vLPEV2tG0leis1Ult
# 5a/dm2tjIF2OfjuyQ9hiOpTlzbSYszcZJBJyc6sEsAnchebUIgTvQCodLm3HadNu
# twFsDeCXpxbmJouI9wNEhl9iZ0y1pzeoVdwDNoxuz202JvEOj7A9ccDhMqeC5LYy
# AjIwfLWTyCH9PIjmaWP47nXJi8Kr77o6/elev7YR8b7wPcoyPm593g9+m5XEEofn
# GrhO7izB36Fl6CSDySrC/blTAgMBAAGjggGtMIIBqTAOBgNVHQ8BAf8EBAMCAYYw
# EwYDVR0lBAwwCgYIKwYBBQUHAwMwEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNVHQ4E
# FgQUJZ3Q/FkJhmPF7POxEztXHAOSNhEwHwYDVR0jBBgwFoAUHwC/RoAK/Hg5t6W0
# Q9lWULvOljswgZMGCCsGAQUFBwEBBIGGMIGDMDkGCCsGAQUFBzABhi1odHRwOi8v
# b2NzcC5nbG9iYWxzaWduLmNvbS9jb2Rlc2lnbmluZ3Jvb3RyNDUwRgYIKwYBBQUH
# MAKGOmh0dHA6Ly9zZWN1cmUuZ2xvYmFsc2lnbi5jb20vY2FjZXJ0L2NvZGVzaWdu
# aW5ncm9vdHI0NS5jcnQwQQYDVR0fBDowODA2oDSgMoYwaHR0cDovL2NybC5nbG9i
# YWxzaWduLmNvbS9jb2Rlc2lnbmluZ3Jvb3RyNDUuY3JsMFUGA1UdIAROMEwwQQYJ
# KwYBBAGgMgECMDQwMgYIKwYBBQUHAgEWJmh0dHBzOi8vd3d3Lmdsb2JhbHNpZ24u
# Y29tL3JlcG9zaXRvcnkvMAcGBWeBDAEDMA0GCSqGSIb3DQEBCwUAA4ICAQAldaAJ
# yTm6t6E5iS8Yn6vW6x1L6JR8DQdomxyd73G2F2prAk+zP4ZFh8xlm0zjWAYCImbV
# YQLFY4/UovG2XiULd5bpzXFAM4gp7O7zom28TbU+BkvJczPKCBQtPUzosLp1pnQt
# pFg6bBNJ+KUVChSWhbFqaDQlQq+WVvQQ+iR98StywRbha+vmqZjHPlr00Bid/XSX
# hndGKj0jfShziq7vKxuav2xTpxSePIdxwF6OyPvTKpIz6ldNXgdeysEYrIEtGiH6
# bs+XYXvfcXo6ymP31TBENzL+u0OF3Lr8psozGSt3bdvLBfB+X3Uuora/Nao2Y8nO
# ZNm9/Lws80lWAMgSK8YnuzevV+/Ezx4pxPTiLc4qYc9X7fUKQOL1GNYe6ZAvytOH
# X5OKSBoRHeU3hZ8uZmKaXoFOlaxVV0PcU4slfjxhD4oLuvU/pteO9wRWXiG7n9dq
# cYC/lt5yA9jYIivzJxZPOOhRQAyuku++PX33gMZMNleElaeEFUgwDlInCI2Oor0i
# xxnJpsoOqHo222q6YV8RJJWk4o5o7hmpSZle0LQ0vdb5QMcQlzFSOTUpEYck08T7
# qWPLd0jV+mL8JOAEek7Q5G7ezp44UCb0IXFl1wkl1MkHAHq4x/N36MXU4lXQ0x72
# f1LiSY25EXIMiEQmM2YBRN/kMw4h3mKJSAfa9TCCB6cwggWPoAMCAQICDHJsAG/o
# HyfTg/C2WDANBgkqhkiG9w0BAQsFADBcMQswCQYDVQQGEwJCRTEZMBcGA1UEChMQ
# R2xvYmFsU2lnbiBudi1zYTEyMDAGA1UEAxMpR2xvYmFsU2lnbiBHQ0MgUjQ1IEVW
# IENvZGVTaWduaW5nIENBIDIwMjAwHhcNMjQxMDExMTkxNjI0WhcNMjUxMTI3MTQ0
# NTA0WjCCAQsxHTAbBgNVBA8MFFByaXZhdGUgT3JnYW5pemF0aW9uMRAwDgYDVQQF
# Ewc1NzQzNTgyMRMwEQYLKwYBBAGCNzwCAQMTAlVTMRkwFwYLKwYBBAGCNzwCAQIT
# CERlbGF3YXJlMQswCQYDVQQGEwJVUzEWMBQGA1UECBMNTWFzc2FjaHVzZXR0czET
# MBEGA1UEBxMKQnVybGluZ3RvbjEeMBwGA1UECRMVMTUgV2F5c2lkZSBSZCBTdGUg
# NDAwMSYwJAYDVQQKEx1QUk9HUkVTUyBTT0ZUV0FSRSBDT1JQT1JBVElPTjEmMCQG
# A1UEAxMdUFJPR1JFU1MgU09GVFdBUkUgQ09SUE9SQVRJT04wggIiMA0GCSqGSIb3
# DQEBAQUAA4ICDwAwggIKAoICAQCRlypE6JLwyb1KZBHXlaNNkfr/2K5FnPVyJ1dZ
# 2MzV1dPnP/w150+FYS+CexgEohk15CwL4V+KcXECKdCvcbbLKBSvCnL9Ck1C47jA
# CKsKQZAlD59XeFmdC47gme6g7QrqA//iY9+F56GBhgD96Mr7bQxUHtCbxVKkcBsc
# 3DQyhe9XK1Nf7Q7Xgn3Pjo9nUhrkTdYiQ2XoDK9qZkfWm040nI3lGkkGqpJ59EgL
# xVUsYRRlPIRbJ0VVGONJaL9j7npAdtq4/XvPX1G8pSTFFTHWacAjH0NEIWVAGEtA
# 8eZlfpTVgEoV5CEnt4HT+4NAIsqGfjMAGt2W4iErpk+IIRvs9PzerIoPiZviUQdn
# kMNUhVElt8S9kfJMpEB8v5tnakZsSj2zzR0Q0Q8ju9sLsfKSkKhMVpDS3aD3dwf5
# 5Fd0Od3lc7DHBjGqMgjD6HbpUsAIkxI7VeztAGIWaXfTtCCjiT/V7swaDsNZ39Ws
# c64Ziou3UTe3LTu5BwSN7fk59GCWLhUSjht6jizRtwR8pi+dfKTAnPkF2xXmR764
# 1ELzwOHV6fKwFjfhLX2+xWwFKnAiiEyGfDELeXbd5ERyY+XYPzQiQ/tqnXW683yx
# fvn9JcrbD+yGgm0PB+VYG0oxDXuBuYfAoGBHmZXXyM/3K65QSZNC0aSE4shVufQn
# 164L6wIDAQABo4IBtjCCAbIwDgYDVR0PAQH/BAQDAgeAMIGfBggrBgEFBQcBAQSB
# kjCBjzBMBggrBgEFBQcwAoZAaHR0cDovL3NlY3VyZS5nbG9iYWxzaWduLmNvbS9j
# YWNlcnQvZ3NnY2NyNDVldmNvZGVzaWduY2EyMDIwLmNydDA/BggrBgEFBQcwAYYz
# aHR0cDovL29jc3AuZ2xvYmFsc2lnbi5jb20vZ3NnY2NyNDVldmNvZGVzaWduY2Ey
# MDIwMFUGA1UdIAROMEwwQQYJKwYBBAGgMgECMDQwMgYIKwYBBQUHAgEWJmh0dHBz
# Oi8vd3d3Lmdsb2JhbHNpZ24uY29tL3JlcG9zaXRvcnkvMAcGBWeBDAEDMAkGA1Ud
# EwQCMAAwRwYDVR0fBEAwPjA8oDqgOIY2aHR0cDovL2NybC5nbG9iYWxzaWduLmNv
# bS9nc2djY3I0NWV2Y29kZXNpZ25jYTIwMjAuY3JsMBMGA1UdJQQMMAoGCCsGAQUF
# BwMDMB8GA1UdIwQYMBaAFCWd0PxZCYZjxezzsRM7VxwDkjYRMB0GA1UdDgQWBBR5
# VcHLeGc1Knox1V7EBUmbA6+0eDANBgkqhkiG9w0BAQsFAAOCAgEAFl60PaXiJzyG
# mDap034Aca4ivZWWLaAwGvd8qDBU0Unmb6i2eEIi1CzvyuByEYIfyNysEocglPVV
# HHL7JHZeNuctxV1Xc0HLmc9B+oWtaLu7HWe9gZjiFaplRLKUEABO+Q2Vu1OSA+6H
# +qPFVG187nImRh7KO4lh0rxn0Ntfo5IEWG8/EsRCPcEtPlwg2mxXgK+gLRbxPQzH
# sDRh5IwwkVH/HIPn4ctuq/F4M7CjoHK8n465+73wO9+vIgi07m/A2PflyRvlBzy5
# 4y48C6NBMeNNXQ5PulxlqJV2Qzofa9ZWACZD2aYddK/pj7ddGGLfme5FeNbyGnx0
# Jg24l10LDh+/ellP6NtPb5xbbxZHCh+d+2cRjAEvXCMlm5CK2DJEAwCUDWFS/xoH
# Tmo3gdnPfbx60gzkRocmJFtEVtc0KUFwUruSImEknJqWzqcElX0tyXVlBsEimLWo
# YOVwUi2s/MEpeU2qG2ww+kElkTEIUQeutZZcHpE479im8P4lnq7nXXkBSorFwXIV
# fX9xv8XYydyypuSQiTSa8CPNQEq40MjHQ6C9xJJnY1+6hssNdFcwiK0ioS9zYPaO
# 4uynGYD8rP7TwG0+wTGCZ+Rs753kMy1Z2+lngESQKnXRaUqvu0svO9npasG3gx6V
# /+MHp+VpLjcP1VrGfARV9jOy70pN+WIxghsSMIIbDgIBATBsMFwxCzAJBgNVBAYT
# AkJFMRkwFwYDVQQKExBHbG9iYWxTaWduIG52LXNhMTIwMAYDVQQDEylHbG9iYWxT
# aWduIEdDQyBSNDUgRVYgQ29kZVNpZ25pbmcgQ0EgMjAyMAIMcmwAb+gfJ9OD8LZY
# MA0GCWCGSAFlAwQCAQUAoIHMMBkGCSqGSIb3DQEJAzEMBgorBgEEAYI3AgEEMBwG
# CisGAQQBgjcCAQsxDjAMBgorBgEEAYI3AgEVMC8GCSqGSIb3DQEJBDEiBCAuMGFn
# WRYr1Lz+lzDoKgNzMW5yQL+Pl6XwBj9TjTJVRDBgBgorBgEEAYI3AgEMMVIwUKAw
# gC4AUAByAG8AZwByAGUAcwBzACAAUwBpAHQAZQBmAGkAbgBpAHQAeQAgAEMATQBT
# oRyAGmh0dHBzOi8vd3d3LnByb2dyZXNzLmNvbS8gMA0GCSqGSIb3DQEBAQUABIIC
# ADccG6gC5bUHbbOX5zI3f8/hXiL8XrUA2VrCYp8tIwvq/tjLwB6aDoL0neNrU0xT
# 1dMPwF6F6/utdfqqKW6iP22NqurkNS3ZN0yiRk4ejkz3KxoDQx+CQHzESy9u8Eeq
# pTApgBUzzkuTcsMjy2+zW8gfgfAFIZhxzVFFIbmLNIwDpJnTEPRmsuXoWtEmpie1
# a0zYlgQk3XqyxospFHsgqu/qvPc5maxKfzeXfEHPeLaWXfi7KoGJjM/3Lh9U12TM
# jscG0YQVt7FBURj4C9bt7iUYAbzjYW3zBSpuFjwBrqW5cD1KUGp7QXiJagizH6rN
# 3qxAg2IrhuYlNWUQ01pD783pVZTn6WMh5dmsgRK6vIMVtLdpTGsXGwwrG47Mqb80
# KpsVdTodpAtvAEQwZ/YfdeT1y5JPNAgWgRS3yrzqytzq7o9H1DT+GbwOM+NxhXXP
# YOK685e975v1kj4KxkJ/RRsTw19lOrVRjs2OWfDUdipiTCxHH/9OuhPULBVc6PJ0
# 5K8U+TaNNwtwYZ7QUN3PlpMqmr3PkJuA5w6k2hsug2pdOd4Xt6HmBGrpnnj066eI
# 53iFIFXdnxmEGwyd400uVnF9mewTiKAe1MCig+LAD2SjZ+zjdczyflriH7SVQWOW
# sBnzHv03WmNN1Gx+CFEcWw0+xdXZpCH0F/pYVYPXWZn+oYIXqDCCF6QGCisGAQQB
# gjcDAwExgheUMIIXkAYJKoZIhvcNAQcCoIIXgTCCF30CAQMxDzANBglghkgBZQME
# AgEFADCCAWkGCyqGSIb3DQEJEAEEoIIBWASCAVQwggFQAgEBBgorBgEEAYRZCgMB
# MDEwDQYJYIZIAWUDBAIBBQAEIEbGuEyWWMAWhaoPbwDdfsW/LbpZevV7qbrU7UA6
# m1eeAgZnEPzkcqwYEzIwMjQxMTAxMDkzNDI1LjcxOVowBIACAfSggeikgeUwgeIx
# CzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRt
# b25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xLTArBgNVBAsTJE1p
# Y3Jvc29mdCBJcmVsYW5kIE9wZXJhdGlvbnMgTGltaXRlZDEmMCQGA1UECxMdVGhh
# bGVzIFRTUyBFU046RjVENi05NkQ2LTkwOUUxNTAzBgNVBAMTLE1pY3Jvc29mdCBQ
# dWJsaWMgUlNBIFRpbWUgU3RhbXBpbmcgQXV0aG9yaXR5oIIPKDCCB4IwggVqoAMC
# AQICEzMAAAAF5c8P/2YuyYcAAAAAAAUwDQYJKoZIhvcNAQEMBQAwdzELMAkGA1UE
# BhMCVVMxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjFIMEYGA1UEAxM/
# TWljcm9zb2Z0IElkZW50aXR5IFZlcmlmaWNhdGlvbiBSb290IENlcnRpZmljYXRl
# IEF1dGhvcml0eSAyMDIwMB4XDTIwMTExOTIwMzIzMVoXDTM1MTExOTIwNDIzMVow
# YTELMAkGA1UEBhMCVVMxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEy
# MDAGA1UEAxMpTWljcm9zb2Z0IFB1YmxpYyBSU0EgVGltZXN0YW1waW5nIENBIDIw
# MjAwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCefOdSY/3gxZ8FfWO1
# BiKjHB7X55cz0RMFvWVGR3eRwV1wb3+yq0OXDEqhUhxqoNv6iYWKjkMcLhEFxvJA
# eNcLAyT+XdM5i2CgGPGcb95WJLiw7HzLiBKrxmDj1EQB/mG5eEiRBEp7dDGzxKCn
# TYocDOcRr9KxqHydajmEkzXHOeRGwU+7qt8Md5l4bVZrXAhK+WSk5CihNQsWbzT1
# nRliVDwunuLkX1hyIWXIArCfrKM3+RHh+Sq5RZ8aYyik2r8HxT+l2hmRllBvE2Wo
# k6IEaAJanHr24qoqFM9WLeBUSudz+qL51HwDYyIDPSQ3SeHtKog0ZubDk4hELQSx
# nfVYXdTGncaBnB60QrEuazvcob9n4yR65pUNBCF5qeA4QwYnilBkfnmeAjRN3LVu
# Lr0g0FXkqfYdUmj1fFFhH8k8YBozrEaXnsSL3kdTD01X+4LfIWOuFzTzuoslBrBI
# LfHNj8RfOxPgjuwNvE6YzauXi4orp4Sm6tF245DaFOSYbWFK5ZgG6cUY2/bUq3g3
# bQAqZt65KcaewEJ3ZyNEobv35Nf6xN6FrA6jF9447+NHvCjeWLCQZ3M8lgeCcnnh
# TFtyQX3XgCoc6IRXvFOcPVrr3D9RPHCMS6Ckg8wggTrtIVnY8yjbvGOUsAdZbeXU
# IQAWMs0d3cRDv09SvwVRd61evQIDAQABo4ICGzCCAhcwDgYDVR0PAQH/BAQDAgGG
# MBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRraSg6NS9IY0DPe9ivSek+2T3b
# ITBUBgNVHSAETTBLMEkGBFUdIAAwQTA/BggrBgEFBQcCARYzaHR0cDovL3d3dy5t
# aWNyb3NvZnQuY29tL3BraW9wcy9Eb2NzL1JlcG9zaXRvcnkuaHRtMBMGA1UdJQQM
# MAoGCCsGAQUFBwMIMBkGCSsGAQQBgjcUAgQMHgoAUwB1AGIAQwBBMA8GA1UdEwEB
# /wQFMAMBAf8wHwYDVR0jBBgwFoAUyH7SaoUqG8oZmAQHJ89QEE9oqKIwgYQGA1Ud
# HwR9MHsweaB3oHWGc2h0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY3Js
# L01pY3Jvc29mdCUyMElkZW50aXR5JTIwVmVyaWZpY2F0aW9uJTIwUm9vdCUyMENl
# cnRpZmljYXRlJTIwQXV0aG9yaXR5JTIwMjAyMC5jcmwwgZQGCCsGAQUFBwEBBIGH
# MIGEMIGBBggrBgEFBQcwAoZ1aHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9w
# cy9jZXJ0cy9NaWNyb3NvZnQlMjBJZGVudGl0eSUyMFZlcmlmaWNhdGlvbiUyMFJv
# b3QlMjBDZXJ0aWZpY2F0ZSUyMEF1dGhvcml0eSUyMDIwMjAuY3J0MA0GCSqGSIb3
# DQEBDAUAA4ICAQBfiHbHfm21WhV150x4aPpO4dhEmSUVpbixNDmv6TvuIHv1xIs1
# 74bNGO/ilWMm+Jx5boAXrJxagRhHQtiFprSjMktTliL4sKZyt2i+SXncM23gRezz
# soOiBhv14YSd1Klnlkzvgs29XNjT+c8hIfPRe9rvVCMPiH7zPZcw5nNjthDQ+zD5
# 63I1nUJ6y59TbXWsuyUsqw7wXZoGzZwijWT5oc6GvD3HDokJY401uhnj3ubBhbkR
# 83RbfMvmzdp3he2bvIUztSOuFzRqrLfEvsPkVHYnvH1wtYyrt5vShiKheGpXa2AW
# psod4OJyT4/y0dggWi8g/tgbhmQlZqDUf3UqUQsZaLdIu/XSjgoZqDjamzCPJtOL
# i2hBwL+KsCh0Nbwc21f5xvPSwym0Ukr4o5sCcMUcSy6TEP7uMV8RX0eH/4JLEpGy
# ae6Ki8JYg5v4fsNGif1OXHJ2IWG+7zyjTDfkmQ1snFOTgyEX8qBpefQbF0fx6URr
# YiarjmBprwP6ZObwtZXJ23jK3Fg/9uqM3j0P01nzVygTppBabzxPAh/hHhhls6kw
# o3QLJ6No803jUsZcd4JQxiYHHc+Q/wAMcPUnYKv/q2O444LO1+n6j01z5mggCSlR
# wD9faBIySAcA9S8h22hIAcRQqIGEjolCK9F6nK9ZyX4lhthsGHumaABdWzCCB54w
# ggWGoAMCAQICEzMAAAA/BBrpfm0n/usAAAAAAD8wDQYJKoZIhvcNAQEMBQAwYTEL
# MAkGA1UEBhMCVVMxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEyMDAG
# A1UEAxMpTWljcm9zb2Z0IFB1YmxpYyBSU0EgVGltZXN0YW1waW5nIENBIDIwMjAw
# HhcNMjQwNDE4MTc1OTEyWhcNMjUwNDE3MTc1OTEyWjCB4jELMAkGA1UEBhMCVVMx
# EzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoT
# FU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEtMCsGA1UECxMkTWljcm9zb2Z0IElyZWxh
# bmQgT3BlcmF0aW9ucyBMaW1pdGVkMSYwJAYDVQQLEx1UaGFsZXMgVFNTIEVTTjpG
# NUQ2LTk2RDYtOTA5RTE1MDMGA1UEAxMsTWljcm9zb2Z0IFB1YmxpYyBSU0EgVGlt
# ZSBTdGFtcGluZyBBdXRob3JpdHkwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIK
# AoICAQCmvHbRVVmoQX72/CJp7W/2ua+rmBXIW4DLqRl+VuezI4WdYTfJssiMVSZb
# iDDwa0dKFKbONar4v3XY5fRuJpgcdiR+8kLXd81G5kZvRwGtSQEx1YhLqNJtwkf9
# EHEyE0rtYPhH89OLJeUXcLQcHPt6SgR2zwi+wODWRxiRCsHfiihiTFYV+DdP62PO
# lq6fqCcRMGwE2CnolunCAp6KJsAdL2WdjWkjt9Hkf1W0zBnpiVWYyGoEOdYe4DM7
# uJ5irz3Ag07e1ZDoPgKbLxKWFmfiwxCd6V1YDXFQPEJhAZIoECKRwC8kJB1kOAQn
# 7LARqlcHaImy6WkMok3UFW2wO5T1bqt/jBFsOvGPb8s+toixse385IfDXypb6RDD
# YcCG94CLs/gjyd9NqEczarc0f9JMdzbJmnhGhYQVhL0qjO4A2aYBZxMfXliEgbSu
# coURhExB4leILpt7JfCsxFdGm4MDqIoSvoYpIP4zjDNrw+dyw+TABLZkvIugz7AF
# DMddbmIr7MCO/4RuKjtN8iTRpdm3zchE6FiJG5t7nPPXmq4ZL8P+BUhOzE1dpVFc
# muuXAodoZHFNbsRH9CB20l5W132AIPH45lRbQj54TVNORnrC4T/Q0/HWvOaKvw1o
# IR/BSvo+qsxXOCWPLueYEBkgIDGppSlJ1LRB8YXnEmRjTEFrcwIDAQABo4IByzCC
# AccwHQYDVR0OBBYEFAH0+2uVLC+pzWsJN3mQ2J38lOLXMB8GA1UdIwQYMBaAFGtp
# KDo1L0hjQM972K9J6T7ZPdshMGwGA1UdHwRlMGMwYaBfoF2GW2h0dHA6Ly93d3cu
# bWljcm9zb2Z0LmNvbS9wa2lvcHMvY3JsL01pY3Jvc29mdCUyMFB1YmxpYyUyMFJT
# QSUyMFRpbWVzdGFtcGluZyUyMENBJTIwMjAyMC5jcmwweQYIKwYBBQUHAQEEbTBr
# MGkGCCsGAQUFBzAChl1odHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2Nl
# cnRzL01pY3Jvc29mdCUyMFB1YmxpYyUyMFJTQSUyMFRpbWVzdGFtcGluZyUyMENB
# JTIwMjAyMC5jcnQwDAYDVR0TAQH/BAIwADAWBgNVHSUBAf8EDDAKBggrBgEFBQcD
# CDAOBgNVHQ8BAf8EBAMCB4AwZgYDVR0gBF8wXTBRBgwrBgEEAYI3TIN9AQEwQTA/
# BggrBgEFBQcCARYzaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9Eb2Nz
# L1JlcG9zaXRvcnkuaHRtMAgGBmeBDAEEAjANBgkqhkiG9w0BAQwFAAOCAgEAjVqp
# LSZtsOR7gzRgQg7yZWfMYF4o6sjs0DAGiPEjgVFs8xm8NWhasVto2io+3PqIh0xS
# +dCdOznVJwl7zTnI31f+IHKcRIu75MAyPCm6qnZxtecVWIaXt/NoHhV5SJPap4Xt
# vkXdyk0p0n0krp3uCdHG/ldS+kJ1naiajb5wJCZZ+Jo6GhNXYlDIfjyCOMMRsncK
# Ku58kT47EN3C53ZKLcCfqq0GwRkfoCcwtyCNhoZMAd+L8L18jzjcfTEU1gJ1uviq
# AqA90hEk+qAV8YJY3v6E4dGfBY/otmQlMI4eP8FNIQeaSwMhx+V8jHsF/zOvZH6a
# c4+a8BCkov8E13xa1GE/yRyH+Qac45Z46eJzMynZu1CRfm8Gd3nUup2QFZlGa7R3
# LnMgnD95Jg8Pgbi8UxTS3ieeSs7nJcBmQ/EFTI9Mhbmw/ETrJx3CSdmBrXRRTUfg
# iMx1nvp+Z4oyPpkUcJDGttpYLnkPEV3FzpJIEqO966VltWpi51wLHmDUOrOxE6zV
# zIeKTeqzW4VHRGZxc2DEC+AKs45Gdbkaz64jqIYsnC93ojXVAAccHJpYRDTkavrW
# YBg7qUfe14hg5r+pJVqGITezhPbWchXF5Gb0WagzGlCulRzl9VeDMsFheu4i0Y0A
# G/TwL7HH0avgs/YADDrFqDIztCJ6fVZY5k0NNhIxggbMMIIGyAIBATB4MGExCzAJ
# BgNVBAYTAlVTMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xMjAwBgNV
# BAMTKU1pY3Jvc29mdCBQdWJsaWMgUlNBIFRpbWVzdGFtcGluZyBDQSAyMDIwAhMz
# AAAAPwQa6X5tJ/7rAAAAAAA/MA0GCWCGSAFlAwQCAQUAoIIEJTARBgsqhkiG9w0B
# CRACDzECBQAwGgYJKoZIhvcNAQkDMQ0GCyqGSIb3DQEJEAEEMBwGCSqGSIb3DQEJ
# BTEPFw0yNDExMDEwOTM0MjVaMC8GCSqGSIb3DQEJBDEiBCDzcQtalmEA66bjL1G4
# b9+iI8LOmM2Gxip3edaVOXC4jjCBuQYLKoZIhvcNAQkQAi8xgakwgaYwgaMwgaAE
# ICvkwWcNF2visOVggae2UjSHxSin6gkv67uErp2wPOuaMHwwZaRjMGExCzAJBgNV
# BAYTAlVTMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xMjAwBgNVBAMT
# KU1pY3Jvc29mdCBQdWJsaWMgUlNBIFRpbWVzdGFtcGluZyBDQSAyMDIwAhMzAAAA
# PwQa6X5tJ/7rAAAAAAA/MIIC5wYLKoZIhvcNAQkQAhIxggLWMIIC0qGCAs4wggLK
# MIICMwIBATCCARChgeikgeUwgeIxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNo
# aW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
# cG9yYXRpb24xLTArBgNVBAsTJE1pY3Jvc29mdCBJcmVsYW5kIE9wZXJhdGlvbnMg
# TGltaXRlZDEmMCQGA1UECxMdVGhhbGVzIFRTUyBFU046RjVENi05NkQ2LTkwOUUx
# NTAzBgNVBAMTLE1pY3Jvc29mdCBQdWJsaWMgUlNBIFRpbWUgU3RhbXBpbmcgQXV0
# aG9yaXR5oiMKAQEwBwYFKw4DAhoDFQDltFuAbHIFFLNi1JibpFQwn4BcSqBnMGWk
# YzBhMQswCQYDVQQGEwJVUzEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
# MTIwMAYDVQQDEylNaWNyb3NvZnQgUHVibGljIFJTQSBUaW1lc3RhbXBpbmcgQ0Eg
# MjAyMDANBgkqhkiG9w0BAQUFAAIFAOrOmPUwIhgPMjAyNDExMDEwMDAxNTdaGA8y
# MDI0MTEwMjAwMDE1N1owdzA9BgorBgEEAYRZCgQBMS8wLTAKAgUA6s6Y9QIBADAK
# AgEAAgIPJgIB/zAHAgEAAgIRVjAKAgUA6s/qdQIBADA2BgorBgEEAYRZCgQCMSgw
# JjAMBgorBgEEAYRZCgMCoAowCAIBAAIDB6EgoQowCAIBAAIDAYagMA0GCSqGSIb3
# DQEBBQUAA4GBAAWx7A1RlSR1zb/SQ8L6E9/9pN9OHSqaBkHu4LB4oD5lTMYystOd
# 3FfXjj96kaKZpTcWHby4N72pPlshFVsCDGuhknUcndSxZ0cQuxvf13COS/cG1E5Z
# DyXpOtrLgM5+3FZjEDTE5nV2jfJhsQ7HDoGuNElQTuK426hkR52H5dCYMA0GCSqG
# SIb3DQEBAQUABIICAFcsYNlQyN6K/GGwPqM7olDRwyj4PN15pBszsuURT0GRNOfL
# UfjAQDL23nXjr2zH1qoNEEDSg/xnRp/NEqncCt0FUD+UptHuO7dfwUEkgBSO4g9d
# lH5XW/tjDC2D3cWI63rcfPgNz6DbP0Tu8epP3z4EqjvbyUA3JIgN+7R0LuN4PFSO
# IipsFgRcVatTerkNZLL2zUNhR7M2LKTulk2y0HyYKsy3jk3mOXIX5Shdk1+x+3cn
# xCb7yIBloF3mBphWACJLUEo0VMgogo9kMH9WhWbF5YMnJcFl6iYbAyzZmWaphLRa
# 5d46LLrxM44MoBQPILvojKBEw3Wk+psZ0DXH3QX2UT6VXwlFVbdoTDIlpC2v2Il2
# fqXkfyNPayjfEkZRJZmOeJyuus0543xHvF/O/zcuN38WY2cGMKdtdvSEWgwO/BhD
# dwy2KU9qsv7ZkTYcu50Vfbv06Vl0a+soxwkhuHzSmjl/ix/DzvvLuEk8GC24HaDK
# UFOuCYyETSe4W1jgNEXvfqbRLbeujYPQWjqAx42lmhxBEM5DPJYrZhujdo9iiFYx
# b4/vTD+JJYaGsGRNxCGaFjlEqybel/ZnBZ1CDU0vdrxFjiSv/rHmO1j3ap8BkMUO
# GBLTJ1kLl4UFddvBcnC36i2hsMUiLpbGBsI9YUezAyooViX5IgICx0fzvxXw
# SIG # End signature block
